### ISSUE TITLE
index.html Header Tags inside tiles are not correct color

### ISSUE THREAD

**Issue by malsf21** [OBRIEN66/dmcs#1]
Hey there! Just leaving a note, but the coloring for the Headers inside of your site tiles are blackish gray, while the text is white. White is much easier to read than they gray color; I suggest you change the headers to be white as well.

*Hint Hint:* you'll probably do something along the lines of `.tile h1{color:white;}`

**Comment by OBRIEN66** [comment]
Thanks @malsf21 !
